name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below so we can fix it.
  - type: textarea
    id: what_happened
    attributes:
      label: What Happened?
      description: Describe the bug in detail
      placeholder: "The login button doesn't respond when clicked..."
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: How do we recreate the bug?
      placeholder: |
        1. Navigate to /login
        2. Enter email and password
        3. Click "Sign In"
        4. Button does nothing
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "The user should be logged in and redirected to /dashboard"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Logs
      description: Any error messages, console logs, or screenshots?
      placeholder: "Paste error logs or attach screenshots here"
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment (Optional)
      description: Browser, OS, or other relevant details
      placeholder: |
        - Browser: Chrome 120
        - OS: Windows 10
        - Device: Desktop
    validations:
      required: false