name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below to help us fix it.
  - type: textarea
    id: what_happened
    attributes:
      label: What Happened?
      description: Clear description of the bug
      placeholder: "e.g., The login button doesn't respond when clicked"
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Open the app
        2. Navigate to the login page
        3. Click the login button
        4. [Bug occurs]
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "e.g., The login button should submit the form and redirect to the dashboard"
    validations:
      required: true
  - type: textarea
    id: screenshots_logs
    attributes:
      label: Screenshots / Logs
      description: Paste error messages, logs, or add screenshots
      placeholder: "Optional: error trace, console logs, screenshots"
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Browser, OS, or other relevant details
      placeholder: |
        Optional:
        - Browser: Chrome 120
        - OS: Windows 11
        - Device: Desktop
    validations:
      required: false